# Generated by Django 2.1.5 on 2019-01-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateField(default='2019-01-15')),
                ('due_date', models.DateField(default='2019-01-15')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
